{{- if .Values.ingress.internal.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-internal
  namespace: {{ .Values.namespace.name }}
  annotations:
    {{- with .Values.ingress.internal.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ .Values.app.name }}
    access: internal
    ingress-type: internal
spec:
  ingressClassName: {{ .Values.ingress.internal.className }}
  rules:
  - http:
      paths:
      {{- range .Values.ingress.internal.paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $.Values.app.name }}
            port:
              number: {{ $.Values.service.port }}
      {{- end }}
{{- end }}
